### ISSUE TITLE
The Shop page should not reload when an Ajax filtering plugin for WooCommerce is enabled

### ISSUE THREAD

**Issue by Rale379** [bhadaway/generic-theme#10]
Thank you for this wonderful theme ❤

I’ve installed the plugin for Ajax filtering of WooCommerce products:
WOOF – Products Filter for WooCommerce 
https://wordpress.org/plugins/woocommerce-products-filter/
It works properly on other themes. But, on Generic, when a checkbox is selected, the whole page reloads.
This is very inconvenient when trying to select many attributes.
On mobile, the user has to wait for the page, scroll to the Filter button, open, scroll to the filter, select and repeat for each attribute.

If possible, could you please give me a code snippet that I can add to the website, to not have to wait for the theme update.
Thank you

**Comment by bhadaway** [comment]
This might again be a job for `add_theme_support( 'woocommerce' );`. Let me know if it works.

**Comment by Rale379** [comment]
It was. It does. 👌👍

**Comment by bhadaway** [comment]
Awesome. You're welcome.
