### ISSUE TITLE
On the single product page, Comments are displayed instead of Reviews

### ISSUE THREAD

**Issue by Rale379** [bhadaway/generic-theme#11]
No Review option on the WooCommerce single product page. 
Instead there is a Comment section, as if it was a blog post.

**Comment by bhadaway** [comment]
Ah ha! I know that adding `add_theme_support( 'woocommerce' );` to _functions.php_ does in fact fix this one. It'll be in the next official update.

**Comment by Rale379** [comment]
Good one! It did in fact do the trick
Thank you ♪♫♬
