### ISSUE TITLE
Please, add a separate sidebar for Archive pages

### ISSUE THREAD

**Issue by Rale379** [bhadaway/generic-theme#12]
The blog Archive and the WooCommerce Shop page need their own sidebars, that are naturally different and don’t appear on other pages.

A useful feature would be to have the sidebar in a modal pop up for mobile devices, with a sticky ’Filters’ button above the products grid.

**Comment by bhadaway** [comment]
Does adding `add_theme_support( 'woocommerce' );` to _functions.php_ help address this problem?

**Comment by Rale379** [comment]
All right! :) Super nice
The products container is now full width and the are filters below it, but it works.

Oh... This is for a defend issue. No, every page still has the same sidebar
But, Ajax is working ッ

**Comment by bhadaway** [comment]
Okay, then unfortunately, I think I'm gonna mark this one as "won't fix" cause I just don't wanna add any more sidebar junk beyond the vanilla primary sidebar. Personally, I stopped using sidebars years ago and a lot of designs no longer use them, but I'm not a complete monster, so at least the main sidebar will stay. ;)

**Comment by Rale379** [comment]
How about removing the sidebar for all other pages?
Because, that's what I'll try to do if you are leaving is as is

**Comment by bhadaway** [comment]
Well, I did change the way the sidebar is called, which will be in the next update. Instead of calling it in every single template, it's now called just once from _footer.php_, `<?php get_sidebar(); ?>`.

But for now, some clunky CSS otta do the trick:

```
#sidebar {
	display: none;
}

.archive #sidebar, .woocommerce #sidebar {
	display: block;
}
```

And then finish it off with one of those conditional widget plugins:

https://wordpress.org/plugins/search/conditional+widgets/

**Comment by Rale379** [comment]
Interesting solution. Wouldn't have assumed that there is a plugin for that.
So, this is the best way to do it, until the update...
Then I'll try to find a php snippet for removing it on all pages except Shop.
Thank you

**Comment by bhadaway** [comment]
Well, the update will only be helpful if you want to make a child theme and then put some conditional logic in _footer.php_.

If you want, at that time, you'll basically just update:

`<?php get_sidebar(); ?>`

to:

`<?php if ( is_archive() || is_woocommerce ) { get_sidebar(); } ?>`

_Untested._

**Comment by Rale379** [comment]
I'm trying to avoid making a child theme and installing plugins.
Would a snippet found on these pages do the trick?
https://stackoverflow.com/questions/49521577/remove-woocommerce-sidebar-from-any-theme
https://stackoverflow.com/questions/35651728/woocommerce-how-to-remove-sidebar

**Comment by bhadaway** [comment]
If you want to avoid a child theme, CSS is always the best way to go:

```
.woocommerce #sidebar {
	display: none;
}
```

**Comment by Rale379** [comment]
You're right. 
I'm overcomplicating it.
CSS and Conditional Widgets plugin it is
