### ISSUE TITLE
The 'Edit This' link is unnecessary

### ISSUE THREAD

**Issue by Rale379** [bhadaway/generic-theme#13]
On every page, there is an 'Edit This' link.
We have the Edit Page / Post / Product option in the WordPress top bar.
Only the Admin can see the link. And I can hide it with CSS...
But, I'm just nitpicking here, in an effort to help perfect the theme
Thank you

**Comment by bhadaway** [comment]
The reason for this is also probably a little selfish. I find the admin bar intrusive and obnoxious and disable it, personally. However, I know there are also enough other people, especially those that are running membership sites that have completed disabled it as well. So, we'll leave this one.
