### ISSUE TITLE
A few CSS properties that I believe would be better to leave out

### ISSUE THREAD

**Issue by Rale379** [bhadaway/generic-theme#14]
- The `transition` property set on `*` will mess up the animation of some plugins
I think that this should be removed for the benefit of novice users that would assume that the plugin is not functioning properly, when it's actually the theme causing a conflict.
On a WooCommerce Quick View plugin the sliding animation of previews was not working as designed.
Plugin - Product Preview for WooCommerce: https://wordpress.org/plugins/product-preview-for-woocommerce/
```
* {
    box-sizing: border-box;
    -webkit-tap-highlight-color: transparent;
    transition: all 0.5s ease;
}
```

- Also, if we are talking about appealing to the masses, underlining every link is not common practice anymore.
Only links inside of a paragraph should be blue or underlined.

 - The `li` tag has a `before `element
I don’t see the benefit. It makes a page look broken.
```
.entry-content ul li::before, 
.widget-container ul li::before, 
.comment-body ul li::before {
    position: absolute;
    margin-left: -20px;
    content: "— ";
}
```
<img width="810" alt="Generic" src="https://user-images.githubusercontent.com/87485693/149628793-ac475d4a-6ca0-4fbb-aeed-b1235aef18b8.png">

**Comment by bhadaway** [comment]
You're 100% correct, and these are all issues I'm aware of.

And yet, I'm not totally certain I want to change these.

As much as Generic is a tool for everyone, it's also a tool for me and my own workflow.

Generic is definitely more aggressive and opinionated than say BlankSlate (https://wordpress.org/themes/blankslate/), where I focus harder on not misbehaving.

Grumble. I won't mark this as "won't fix," but I'll probably stare at the "enhancement" label for a long time. Sorry.

**Comment by Rale379** [comment]
Okay... Now I'm having second thoughts.
Are there other oddities that I should be concerned about?
Also, how likely are you to misbehave in a way that will mess up a website I've built?

I definitely want the CSS that Generic has, because it makes buttons and forms look good on all browsers.
I don't want to keep track of Safari, Mozilla and Edge quirks. The Automattic team does. You transfer over the changes to the theme and I update it - Happy Days

Please, consider having these solutions that improve your workflow, not coded into the theme. (Unlikely, I know. Soo... ⬇ ⬇️)

I can see that you already have 6 themes published. So, how about option B - Create a Goldilocks theme, that anyone can use ''au naturel'' or with their page builder of choice.

I'm active in many WordPress related Facebook groups. And I want to be able to recommend Generic, without caveats

**Comment by bhadaway** [comment]
Nope, you definitely found the two most opinionated parts of the theme:

1. Applying transitions to everything (this one is actually fairly safe, with the rare quirk).
2. Changing the list style (the biggest problem here is the the `content` way of changing the style, which causes enough quirks to be annoying).

I'm not sure I want to completely abandon them, but making them safer is definitely a consideration.

**Comment by bhadaway** [comment]
Gotta love CSS. Give it a few years, and there will always be a cleaner way.

So far, simply replacing:

```
.entry-content ul li::before, .widget-container ul li::before, .comment-body ul li::before {
	position: absolute;
	margin-left: -20px;
	content: '— ';
}
```

with:

```
.entry-content ul li, .widget-container ul li, .comment-body ul li {
	list-style-type: '— ';
}
```

Seems to do the trick.

`list-style: none;` overrides `list-style-type`, so I think that's it. One down.

**Comment by Rale379** [comment]
2. Changing the list style
OK, I have added `list-style-type: '— ';`  
Working well and looking good. And it's not showing up on the Shop page in a weird way.

1. Applying transitions to everything 
Quirks will be rare on basic pages. But on feature packed websites, like this Shop page I'm working on, there will be many.
- When hovering a menu link, text color changes take too long
- When using the Quick View feature, the sliding animation breaks
- When closing filters pop up for mobile, the checkboxes take very long do disappear. Probably do to the large DOM
Here's a video of it: https://streamable.com/lkbufg

''Thanks for the nudge''. You are very welcome. Thank you for a great theme.

Strange though, that I'm the first one to bring up the incompatibility with WooCommerce.

I'm quite happy to nitpick, because it's soo close to perfection, in my opinion.

Can you share the secret sauce? What are you doing to it?
I've tested it against a few Undercsores based themes, Hello and Skelementor.
It outperforms everything. LCP is faster then Underscores by 1 second and 0.5 s faster than Hello.
This shop page I'm testing is packed with every possible Ajax powered plugin: filters, sorting, pagination, quick view, wishlist, search with dropdown recommendations, on-hover menu cart, ajax add to cart...
No caching or CDN. Not doing any asset cleanup. So, plugins from other pages are loading their junk as well.
DigitalOcean has been having major swings since the beginning of the year. So, the Page Speed Insights scores will vary from below 80 to over 90 points, but 85 on most days. Which I think is great, for a website with so many plugins.
But, it's not a trick to fool the test, that some caching plugins do. The backend and the frontend feels quicker.
https://postimg.cc/MvFrD1BQ

**Comment by bhadaway** [comment]
To put it simply, in the world of WordPress, 1,000 users is nothing. Hardly enough users to get much feedback. BlankSlate has 10k users, and that's only just starting to scratch the surface of more substantial. 100k users? Then we'd have a community and the project would get more love. Plus a lot of users are using child themes. In fact, that's probably the most popular way to use Generic, so they're just removing anything they don't like.

The other themes you mentioned are just not as lightweight. They tend to be integrating entire third-party libraries like Bootstrap, along with more JS, back-end settings, and dozens of people submitting code to them. I'm just one person and I try to keep things as simple as possible. I'm not a complete purest; I do use some third-party scripts, but where possible, I keep everything as simple, clean, and minified as I can.

Are you using WP Rocket to optimize your site?

You might roll your eyes at this cause I know what you really want me to do, but would you mind testing this out?:

```
* {
	transition: unset;
}
```

**Comment by Rale379** [comment]
I run a LietSpeed VPS with CyberPanel.
So, when I do turn on caching, it will be LietSpeed cache.

Not sure what you think I want you to do... :)
I do want the theme to just work, out of the box, and gain the following it should have.
And I did not roll my eyes, because that's the first thing I did - fix the 3 CSS quirks I saw.
So, I know that `transition: unset;` works.

**Comment by bhadaway** [comment]
😝 You want me to take that transition out behind the barn, but I'm gonna leave it.

I've really come to the belief that it's just how everything should transition, by default. Maybe it'll even become so common, that eventually that's how things will behave even at the browser-level, and rather than implementing it, people will have to unset it.

My 🧠 might be broken on this one, but I like it and it stays.

**Comment by bhadaway** [comment]
Alright, I've pushed all the updates to GitHub now, if you'd like the opportunity to review before I push them live officially to WordPress.org.

**Comment by Rale379** [comment]
I only know CSS and can understand a little bit of PHP. So, checking if what you've done is good and ready to ship, is way over my head ✈️

But, I can see that you've moved ` <?php get_sidebar(); ?>` to the footer

You've added the `list-style-type` property and removed the `:before` element

Surprised to see that the link underline `a:-webkit-any-link` seems to be removed 👌 Didn't think that you would budge on that one 

You forgot to remove `transition: all 0.5s ease;` from the asterisk 😜 Though, I really wish you would.
I understand what you are saying. But, it messed up 1 page in 3 places, that I know of.
I think that it's the kind of thing that might deter people from sticking with the theme and will make them wonder if they should trust the developer with their website.
It will be seen as an error that no one has addressed for 4 years.
And that bothers me, because I don't want the theme to be abandoned because the community didn't show interest. 

Do you check if the theme needs some security oriented updates or code updates to look and work properly on every browser?
The reason why I decided to switch from Hello, is because the Sort By dropdown looked odd on the Opera browser on my phone.
I'd like to think that the theme developer is keeping track of these things.
That's really all I need from a theme, to not have to check what a form looks like on Safari, because I don't own Apple devices.

**Comment by bhadaway** [comment]
I really don't think the transition is all that big of a deal, certainly not to the extent that you're making it out to be. It's not a detriment to the popularity of the tool or whether people will try it out, or anything like that. I've been doing this for many years, and I can promise you that even if the transition style was never there, there would still only be 1,000+ active users. There are MANY thousands of themes and plugins for people to choose from, and it's normal that user growth is this slow.

If the community grows and several people vote the transition out, it'll be gone.

I'm OCD; I pay attention to the details. Yes, the code follows the security standards set by WordPress (but there's also a lot more going on that you might not be aware of concerning web standards, valid code, speed, SEO, schema, accessibility, etc.), and inadvertently goes throw the review process again and again in a way. For example, every theme I submit to WordPress is built on top of Generic, so every time there's a new requirement or suggestion, those updates trickle back down to Generic.

Everything found on https://generic.tools/ are my foundational tools for all personal and client projects, and they continue to evolve with the times. They're not cutting edge by any means (that's where you really get into trouble with cross-browser compatibility), but for the most part, very stable.

Even if you're not a developer, it sounds like you're still going down this rabbit hole, at least as a hobby. I highly recommend using Firefox as your default browser, and their Developer Tools:

https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

Just right-click on a page to inspect (you may even already be doing this) and then select the little device icon to switch to Responsive Design Mode.

Anyway, it's closing time and I'm going to push the update live now.

I'll be around if you need me. Thanks for the feedback.

**Comment by Rale379** [comment]
Alright. I'm probably wrong. And, when the transition works as intended, it does look cool, I agree.

''...those updates trickle back down to Generic.'' - Love that

I will dive into it tomorrow... But just a heads up, the video on this page is widening the screen: https://generic.tools/template/

Tried Firefox about a year ago. It was not noob friendly. Wasn't showing/coloring paddings and margins like Chrome. The style suggestions when you start typing, were not on point either. But, things seem to have changed 

I really appreciate being able to contact you. Thank you for the theme and the support

**Comment by bhadaway** [comment]
Thanks for the heads up. Fixed.

**Comment by Rale379** [comment]
Did I misunderstand that you were going to remove the list `before` element or did you forget?
```
.entry-content ul li::before, .widget-container ul li::before, .comment-body ul li::before {
    position: absolute;
    margin-left: -20px;
    content: "— ";
}
```
Links still underlined... probably on purpose.

Not trying to beat a dead horse here, but maybe you should have a page describing the features that make the theme less... well Generic, if that makes sense. I was expecting to find that info and learn more.

The CSS Grid is an interesting page.

**Comment by bhadaway** [comment]
Didn't forget:

https://github.com/bhadaway/generic-theme/blob/master/style.css#L44-L48
