### ISSUE TITLE
Upgrade to php 8.2 broke website using WP-Generic

### ISSUE THREAD

**Issue by BeginnerOne** [bhadaway/generic-theme#18]
I am not a very technical admin. 
I received an email from the ISP Hostgator that I needed to update the site's PHP version to 8+. 
I modified the PHP designation to inherit the version of PHP from their server. 
The website appeared to be operating normally after my changes to the settings but I might have viewed cached versions. 
Now I was checking email and received an email saying there was a critical error on my website.  
----  copied from email -----
WordPress has a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
In this case, WordPress caught an error with your theme, WP Generic.
First, visit your website (https://ponc.org/) and check for any visible issues. Next, visit the page where the error was caught (https://ponc.org/wp-login.php?wp_lang=en_US) and check for any visible issues.
---- 
I downloaded another theme and activated it and the website is operational, but looks like crap. 
The website is www.ponc.org, a website for a regional dog breed club.

Hostgator in their email stated it was not possible to go back to a previous version of PHP. 
Do you have any guidance on how to get WP-Generic theme working again?  

Thanks for any help you can provide. 

Dan Carr

**Comment by bhadaway** [comment]
You're most likely confusing my theme for another, which is understandable.

Here's my theme: https://wordpress.org/themes/generic/

I'm pretty sure you're talking about this theme though: https://beautifulthemes.com/themes/wp-generic/

I was able to track down the original author, but it looks like they've retired the theme (and possibly retired from theme development altogether), which means unless you want to hire someone privately to fix the theme, it's time to switch.

If you want to try some of their other themes or try reaching out to their support, here are the links:

https://wordpress.org/themes/author/8degreethemes/
https://8degreethemes.com/

If you need more help, I'm available (bhadaway@gmail.com).
