### ISSUE TITLE
child theme header.php not working?

### ISSUE THREAD

**Issue by aberling** [bhadaway/generic-theme#5]
First, thank you for the theme!!
Trying to create a line of text/headline above the main/content area and the sidebar that could either pull the title from the post/page or be added via the page/post editor. I thought the easiest way would be to add a new div just inside the "container". This worked fine when I added it to the header.php in the parent theme, but not the header.php file added to the child theme.
Any ideas or workarounds?
I thought about using ::before, but this isn't an ideal option.

**Comment by bhadaway** [comment]
Can you please share copy of your child theme header.php? Use https://pastebin.com/ if needed.
